-- SupplyLink Seed Data
-- Run AFTER schema.sql

USE supplylink;

-- Product Categories
INSERT INTO product_categories (name) VALUES
('Grocery'), ('Pharmacy'), ('Stationary'), ('Hardware');

-- Grocery Products
INSERT INTO products (category_id, name) VALUES
(1, 'Rice'), (1, 'Sugar'), (1, 'Oil'), (1, 'Flour'), (1, 'Dal');

-- Pharmacy Products
INSERT INTO products (category_id, name) VALUES
(2, 'Paracetamol'), (2, 'Antacid'), (2, 'Vitamin'), (2, 'Saline'), (2, 'Cough Syrup');

-- Stationary Products
INSERT INTO products (category_id, name) VALUES
(3, 'Paper'), (3, 'Pen'), (3, 'Notebook'), (3, 'Pencil');

-- Hardware Products
INSERT INTO products (category_id, name) VALUES
(4, 'Cement'), (4, 'Rod'), (4, 'Paint'), (4, 'Screw');

-- Product Variants
-- Rice variants
INSERT INTO product_variants (product_id, variant_name) VALUES
(1, 'Basmati'), (1, 'Miniket'), (1, 'Chinigura'), (1, 'Coarse'), (1, 'Atap'), (1, 'Other');

-- Sugar variants
INSERT INTO product_variants (product_id, variant_name) VALUES
(2, 'White'), (2, 'Brown'), (2, 'Other');

-- Oil variants
INSERT INTO product_variants (product_id, variant_name) VALUES
(3, 'Soybean'), (3, 'Mustard'), (3, 'Palm'), (3, 'Other');

-- Flour variants
INSERT INTO product_variants (product_id, variant_name) VALUES
(4, 'Wheat'), (4, 'Rice'), (4, 'Corn'), (4, 'Other');

-- Dal variants
INSERT INTO product_variants (product_id, variant_name) VALUES
(5, 'Masur'), (5, 'Mung'), (5, 'Chana'), (5, 'Motor'), (5, 'Other');

-- Paracetamol variants
INSERT INTO product_variants (product_id, variant_name) VALUES
(6, '500mg'), (6, '250mg'), (6, 'Other');

-- Antacid variants
INSERT INTO product_variants (product_id, variant_name) VALUES
(7, 'Tablet'), (7, 'Syrup'), (7, 'Other');

-- Vitamin variants
INSERT INTO product_variants (product_id, variant_name) VALUES
(8, 'C'), (8, 'D'), (8, 'B12'), (8, 'Other');

-- Saline variants
INSERT INTO product_variants (product_id, variant_name) VALUES
(9, 'Normal'), (9, 'Other');

-- Cough Syrup variants
INSERT INTO product_variants (product_id, variant_name) VALUES
(10, 'Herbal'), (10, 'Other');

-- Paper variants
INSERT INTO product_variants (product_id, variant_name) VALUES
(11, 'A4 80GSM'), (11, 'A4 70GSM'), (11, 'Legal'), (11, 'Other');

-- Pen variants
INSERT INTO product_variants (product_id, variant_name) VALUES
(12, 'Ball Point'), (12, 'Gel'), (12, 'Other');

-- Notebook variants
INSERT INTO product_variants (product_id, variant_name) VALUES
(13, '100 page'), (13, '200 page'), (13, 'Other');

-- Pencil variants
INSERT INTO product_variants (product_id, variant_name) VALUES
(14, 'HB'), (14, '2B'), (14, 'Other');

-- Cement variants
INSERT INTO product_variants (product_id, variant_name) VALUES
(15, 'OPC 53'), (15, 'OPC 43'), (15, 'PPC'), (15, 'Other');

-- Rod variants
INSERT INTO product_variants (product_id, variant_name) VALUES
(16, '10mm'), (16, '12mm'), (16, '16mm'), (16, 'Other');

-- Paint variants
INSERT INTO product_variants (product_id, variant_name) VALUES
(17, 'Wall'), (17, 'Wood'), (17, 'Other');

-- Screw variants
INSERT INTO product_variants (product_id, variant_name) VALUES
(18, 'M4'), (18, 'M6'), (18, 'M8'), (18, 'Other');

-- Demo admin user (password: demo1234 — hashed with bcrypt)
-- This hash will be generated by the Flask app, but we insert a placeholder
-- The actual login will use the Flask /api/auth/register endpoint
